project:
  type: website
  output-dir: docs
  
  
website:
  title: "new_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      light: minty
      dark: slate
    css: styles.css
    toc: true

editor: visual

